"""add google oauth fields to users

Revision ID: 586d7cfb24eb
Revises: 2b335a0153b7
Create Date: 2026-08-18 20:38:12.082191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '586d7cfb24eb'
down_revision: Union[str, Sequence[str], None] = '2b335a0153b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_provider', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'oauth_provider')
    # ### end Alembic commands ###
